### ISSUE TITLE
Unable to load datapacks on Servers

### ISSUE THREAD

**Issue by NielsPilgaard** [Darkhax-Minecraft/Cauldron-Recipes#2]
- CauldronRecipes-1.15.2-1.1.4
- Forge 1.15.2-31.2.0

[client-latest.og](https://gist.github.com/NillerMedDild/a0065c054cd7d058da87bab17583bd23)
[server-debug.log](https://gist.github.com/NillerMedDild/76e9aa47b0ba7a6e6ebe29eaeeb46fd7)

I cannot connect to my server, because advancements failed to load serverside - Looking into the debug.log, I found the below snippet:

```
[16maj2020 20:24:14.211] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Failed to reload data packs
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.util.JSONUtils.func_151211_a(Lcom/google/gson/JsonElement;)Z
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source) ~[?:1.8.0_241]
	at java.util.concurrent.CompletableFuture.get(Unknown Source) ~[?:1.8.0_241]
	at net.minecraft.server.MinecraftServer.func_195568_a(MinecraftServer.java:1467) [?:?]
	at net.minecraft.server.MinecraftServer.func_195560_a(MinecraftServer.java:450) [?:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:363) [?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:212) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.NoSuchMethodError: net.minecraft.util.JSONUtils.func_151211_a(Lcom/google/gson/JsonElement;)Z
	at net.darkhax.cauldronrecipes.RecipeCauldron$Serializer.readItemStack(RecipeCauldron.java:109) ~[?:1.1.4]
	at net.darkhax.cauldronrecipes.RecipeCauldron$Serializer.readItemStacks(RecipeCauldron.java:147) ~[?:1.1.4]
	at net.darkhax.cauldronrecipes.RecipeCauldron$Serializer.read(RecipeCauldron.java:180) ~[?:1.1.4]
	at net.darkhax.cauldronrecipes.RecipeCauldron$Serializer.func_199425_a_(RecipeCauldron.java:105) ~[?:1.1.4]
	at dev.latvian.kubejs.recipe.RecipeEventJS.post(RecipeEventJS.java:123) ~[?:2.6.1.34]
	at dev.latvian.kubejs.core.RecipeManagerKJS.customRecipesKJS(RecipeManagerKJS.java:21) ~[?:2.6.1.34]
	at net.minecraft.item.crafting.RecipeManager.handler$zzk000$customRecipesHead(RecipeManager.java:1028) ~[?:?]
	at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java) ~[?:?]
	at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:37) ~[?:?]
	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_241]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_241]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_241]
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:731) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:141) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:714) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_195568_a(MinecraftServer.java:1464) ~[?:?]
	... 5 more
```

**Comment by Darkhax** [comment]
Thanks for reporting this. `JSONUtils.func_151211_a` is one of those methods that vanilla never uses on the server so when Mojang builds the game it is removed from the server code. This is now fixed.

**Comment by NielsPilgaard** [comment]
Thank you kindly :)
